### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by worldsdream** [tuxity/insta-unfollower#10]
Hi,

I have python on windows. I installed  the requirements through cmd.
how to run it from cmd? Can you give me the code. Thank you.

`C:\Users\worldsdream\Desktop\insta-unfollower-master\insta-unfollower-master>python insta-unfollower.py
please provide USERNAME and PASSWORD environement variables. Abording...`

**Comment by tuxity** [comment]
Try to set the environment variables USERNAME and PASSWORD in 
```
Control Panel->System and Security -> System -> Advamced system settings->Environmental Variables 
```

**Comment by worldsdream** [comment]
I see User Variables and System Variables. Which one should I add. Do I have to add USERNAME and my username and PASSWORD and the password?

**Comment by tuxity** [comment]
Try User variables first, and yes Variable USERNAME and value your instagram username

**Comment by worldsdream** [comment]
I did add it under User Variables. I am getting the following now after excuting python insta-unfollower.py:

`login failed, verify user/password combination`

**Comment by worldsdream** [comment]
Hi @tuxity. Anything else that I can test. Looking forward to use your program!

**Comment by tuxity** [comment]
I'm going to rewrite a part of the code to avoid this.
Instead of using environment variable only, add the possibility to use parameters

**Comment by mrtancau** [comment]
Hi,
I did that, on comman window:
set USERNAME: MyUsername
set PASSWORD: MyPassword
than I have run --> py myFile.py

Hope this help

**Comment by dagnyforhust** [comment]
Im a bit of a noob at this sort of stuff. Im getting please provide USERNAME and Password even though I have tried adding the environment variables.

**Comment by tuxity** [comment]
@mrtancau your solution works on windows ? Imma update the README if so

**Comment by bikramaryal** [comment]
Does not work on windows

**Comment by tuxity** [comment]
Works for me on Windows 10 and Git Bash with both method (with and without Docker)
