### ISSUE TITLE
KeyError: 'authenticated'

### ISSUE THREAD

**Issue by roccodebellis** [tuxity/insta-unfollower#13]
i run the script on OsX but the script don't work, can u help me ?

`Traceback (most recent call last):`
`    File "insta-follower.py", line 231, in <module>`
`        main()`
`    File "insta-follower.py", line 190, in main`
`        is_logged = login()`
`    File "insta-follower.py", line 55, in login`
`        if response_data['authenticated']:`
`KeyError: 'authenticated'`

**Comment by tuxity** [comment]
I have no problem like this, it must be because instagram block the login for some reasons (wrong pass, new IP, new country .. )
