### ISSUE TITLE
where do I need to put my user IG username an pass?

### ISSUE THREAD

**Issue by hezrei** [tuxity/insta-unfollower#19]
/home/rey/instabot.py/venv/bin/python /home/rey/.cache/.fr-dCJ8vK/insta-unfollower-master/insta-unfollower.py
please provide USERNAME and PASSWORD environement variables. Abording...

**Comment by tuxity** [comment]
Put `USERNAME` and `PASSWORD` before everything.

https://github.com/tuxity/insta-unfollower/blob/master/README.md#without-docker
