### ISSUE TITLE
Script get stuck at

### ISSUE THREAD

**Issue by katepratik** [tuxity/insta-unfollower#2]
script get stuck at building followers list...

Please look into it

**Comment by RaffaeleNachos** [comment]
I think it don't get stuck but it uses a very slow algorithm for building it. If you have more than 1000 followers it will take hours... Just print "test" in the forloop for finding when a person is added in queue.

**Comment by katepratik** [comment]
@RaffaeleNachos Thanks for you reply! I got into the code and made some changes to print logs and tweaked the sleep time too. ;)

**Comment by tuxity** [comment]
@RaffaeleNachos is right, building lists is super slow. I need to review the algorithm but Insta have limitations on their side too when fetching users. For now it's just a rand inside a sleep.

I was thinking few days ago of doing the unfollow at each get when building the lists, but we can't know if the profile is following you. We have to do a comparaison between followers and following lists :/
