### ISSUE TITLE
KeyError: 'data' , weird error i'm getting just after logging in

### ISSUE THREAD

**Issue by neomh** [tuxity/insta-unfollower#3]
You're now logged as XXXX
1314 followers
1958 following
building followers list...
Traceback (most recent call last):
  File "insta-unfollower.py", line 208, in <module>
    main()
  File "insta-unfollower.py", line 180, in main
    followers_list = get_followers_list()
  File "insta-unfollower.py", line 119, in get_followers_list
    for edge in response['data']['user']['edge_followed_by']['edges']:
KeyError: 'data'

**Comment by tuxity** [comment]
Hi,

maybe instagram updated the response format, we need to check that

**Comment by tuxity** [comment]
I've made a fix, tell me if it's okay

**Comment by tuxity** [comment]
Insta send me an error :/ `{'message': 'rate limited', 'status': 'fail'}`

**Comment by neomh** [comment]
script seems to work fine now..

**Comment by tuxity** [comment]
You might want try to increase the sleep timers. Maybe instagram added more security between requests

**Comment by neomh** [comment]
I have to launch the script several times before it works... I don't know what's causing the issue..

**Comment by Markus978** [comment]
After keeping off and not touching my account for 24h it also seems to be running smoothly now. Increasing the sleep timers just delayed the time until the error occurred 🙈

**Comment by ArtFrequencies** [comment]
Not working for me either, I printed the instagram response : 
{'message': 'rate limited', 'status': 'fail'}

**Comment by neomh** [comment]
any news ? not working at all right now..

**Comment by Spreadloveonly** [comment]
Hello everyone, thank you @tuxity for this nice script, unfortunately it dosen't work for me, it's quite weird cause i've got an account with ~120 followings -> the script is working on it, but it doesn't work with an other account that have ~6'000 followings... 

Same error as @neomh on top 
XXX followers
XXX_more than 6'000_XXX following
building followers list...
Traceback (most recent call last):
  File "insta-unfollower.py", line 209, in <module>
    main()
  File "insta-unfollower.py", line 181, in main
    followers_list = get_followers_list()
  File "insta-unfollower.py", line 120, in get_followers_list
    for edge in response['data']['user']['edge_followed_by']['edges']:
KeyError: 'data'

Have a nice day 👍

**Comment by joke4me** [comment]
Same error `KeyError: 'data'` any workaround please

**Comment by Markus978** [comment]
any news here or progress? Error remains unfortunately...

**Comment by tuxity** [comment]
I guess Instagram added more security to detect many requests, for now I don't know how to fix it.

**Comment by tuxity** [comment]
After some tests, the one and only way is to wait few hours for instagram to unblock you.
I ran into the issue when doing some improvements and had to wait
