### ISSUE TITLE
Cant login to my instagram account

### ISSUE THREAD

**Issue by ryahaloms** [tuxity/insta-unfollower#30]
Hi there,
I set the USERNAME and PASSWORD variables correctly but still cannot authenticate my username.

Does this script still works?
Do you need to do anything beforehand?

**Comment by tuxity** [comment]
Sorry for late response but do you have any error message?

Insta have a temp bans over IP when doing too many queries, I recommend you to wait 1 hour or 2 then try again.

I also did a fix for issue #32 maybe it's related ?
