### ISSUE TITLE
Return 400 Bad Request

### ISSUE THREAD

**Issue by IsMMA** [tuxity/insta-unfollower#35]
Lines:

  response = session.post(login_route, data=post_data, allow_redirects=True)
  response_data = json.loads(response.text)

Return Bad Request and finish.

**Comment by IsMMA** [comment]
Any help?

**Comment by joao-gsneto** [comment]
Instagram now uses an encrypted password in frontend.

you can do the login on browser and get the 'enc_password' param and put directly on the source code of the script.

Like:
line 59
```python
post_data = {
        'username': os.environ.get('INSTA_USERNAME'),
        'enc_password': '#PWD_INSTAGRAM_BROWSER:10:(((....restofpassword))',
    }
```

**Comment by tuxity** [comment]
Hello,

I don't have time yet to check it, you have any informations about the encryption method ?

**Comment by tuxity** [comment]
Maybe a start of response here https://github.com/instagrambot/instabot/blob/a15547553600ec8ff54a0c08f6334d9d29981a99/instabot/api/api.py#L216 for a future PR ;)
