### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by yuri25** [tuxity/insta-unfollower#39]
File "insta-unfollower.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by eduardobarbiero** [comment]
try see:

https://github.com/tuxity/insta-unfollower/pull/38/commits/06121d099d98ce696e959ffe83c93fac851ac3d9

**Comment by tuxity** [comment]
Hello,

It should be fixed since a while now. I'm closing the issue, don't hesitate to comment if needed.
