### ISSUE TITLE
How to fetch Current follow requests

### ISSUE THREAD

**Issue by qadirsuh** [tuxity/insta-unfollower#43]
Hi, 
First I appriaciate this wonderful stuff.

I have a little question, can we fetch Current follow requests users list appearing here.
https://www.instagram.com/accounts/access_tool/current_follow_requests

**Comment by qadirsuh** [comment]
Any news on this please. anyone? no one?

**Comment by tuxity** [comment]
Hello,

Can I ask why do you need this ? To refuse the follow request on some conditions ?

**Comment by tuxity** [comment]
Closing the issue since it's not really a problem. Feel free to comment if needed
