### ISSUE TITLE
KeyError: 'authenticated'

### ISSUE THREAD

**Issue by Canorus** [tuxity/insta-unfollower#50]
I know this issue was closed on #13 and #41 but I got something new so I'll just open a new one.

Same error message goes

```
Traceback (most recent call last):
  File "/Users/canor/scripts/insta-unfollower/insta-unfollower.py", line 301, in <module>
    main()
  File "/Users/canor/scripts/insta-unfollower/insta-unfollower.py", line 225, in main
    is_logged = login()
  File "/Users/canor/scripts/insta-unfollower/insta-unfollower.py", line 83, in login
    if response_data['authenticated']:
KeyError: 'authenticated'
```

so I printed `response_data` and it shows

```
{'message': 'checkpoint_required', 'checkpoint_url': '/challenge/224135293/7TSGU0RpjF/', 'lock': False, 'flow_render_type': 0, 'status': 'fail'}
```

what would that mean? any advice would be helpful. thanks.

**Comment by Jookster1** [comment]
I got the exact same error message

**Comment by Canorus** [comment]
just looked up the [internet](https://instazood.com/blog/how-to-fix-checkpoint-required-error-on-instagram/) and learned that Instagram takes this attempt as *suspicious login* and asked me to make sure that _it was me_ on next successful login. However even if I confirmed that it was me Instagram will still block me from signing in. I have no idea how to convince that it's me doing this. probably I'd have to go selenium way.
