### ISSUE TITLE
Error in authentication

### ISSUE THREAD

**Issue by priyanshul-govil** [tuxity/insta-unfollower#51]
Attaching error details below:

```python
Traceback (most recent call last):
  File ".\insta-unfollower.py", line 301, in <module>
    main()
  File ".\insta-unfollower.py", line 225, in main
    is_logged = login()
  File ".\insta-unfollower.py", line 83, in login
    if response_data['authenticated']:
KeyError: 'authenticated'
```

**Comment by rotechcr** [comment]
Login into Instagram Web version, `inspect` and go to the Network tab, choose one of the calls, for example `/get_encrypted_credentials` and make the Request Headers inside `insta-unfollower.py` match with the ones used in the selected call. That's it.

**Comment by priyanshul-govil** [comment]
Alright, got it!
