### ISSUE TITLE
Instagram Security Confirmation

### ISSUE THREAD

**Issue by melocule** [tuxity/insta-unfollower#59]
Hi!

Docker logs `Please check Instagram app for a security confirmation that it is you trying to login.` and the process immediately exits. On the Instagram app I get the "Suspicious login attempt" screen and confirm it was me, but the script doesn't continue and it requests confirmation every time I rerun the script. This issue persists across multiple accounts.

Does this happen on your side?

**Comment by tuxity** [comment]
Hello,

it's like #56 but it should not keep asking you once you click on "it was me". Maybe there is an issue with the docker image and docker network. 

Can you try to tell docker to use the ip of the machine instead of the docker net ip by passing `--network=host` and check if it works

**Comment by basilpapadimas** [comment]
I was experiencing this as well until modifying insta-unfollower.py to report the User-Agent of Safari on the same machine, that fixed it I think

**Comment by basilpapadimas** [comment]
(and I was already logged in to Instagram on Safari)

**Comment by IAMDROPPE** [comment]
Traceback (most recent call last):
  File "C:\Users\DROPPE\Desktop\Help\insta-unfollower\insta-unfollower.py", line 294, in <module>
    main()
  File "C:\Users\DROPPE\Desktop\Help\insta-unfollower\insta-unfollower.py", line 227, in main
    connected_user = get_user_profile(credentials.username)
  File "C:\Users\DROPPE\Desktop\Help\insta-unfollower\insta-unfollower.py", line 89, in get_user_profile
    response = json.loads(extract.group(1))
AttributeError: 'NoneType' object has no attribute 'group'


windows 10
Python 3.10.4
