### ISSUE TITLE
I get this error when running the script, is there a fix to this.

### ISSUE THREAD

**Issue by raj-chinagundi** [tuxity/insta-unfollower#82]
response = session.get(profile_route % (instagram_url, user['username']))
TypeError: not all arguments converted during string formatting

**Comment by raj-chinagundi** [comment]
its in line 157 of the code

**Comment by raj-chinagundi** [comment]
I fixed that `
# TODO: check with the new API
def unfollow(user,headers):
    if os.environ.get('DRY_RUN'):
        return True
    username2=user['username']
    response = session.get(profile_route, params={'username': username2},headers=headers)
` by rewriting it like this

**Comment by raj-chinagundi** [comment]
But now i face another new error ```line 160, in unfollow
    csrf = re.findall(r"csrf_token\":\"(.*?)\"", response.text)[0]
IndexError: list index out of range```

**Comment by pChitral** [comment]
The primary concern arises from the absence of the CSRF token during the unfollowing process. The code appears to be functioning correctly until the point of generating the list; however, it encounters a failure during the unfollowing procedure. I will make an attempt to address this matter.
